Edited the ReadMe.
adam-fowler/aws-cognito-authentication pull request #21
Opened 2021-10-09 08:55 UTC by majortom64

Added one space and an example for using the `CognitoBasicAuthenticator`.

2021-10-09 09:16 UTC, adam-fowler requested changes

2021-10-09 09:16 UTC, adam-fowler commented on README.md
> +An example using `CognitoBasicAuthenticator`:
Given there are two examples perhaps we should give them sub-headings. 
```
### Basic Authenticator Example
```

2021-10-09 09:16 UTC, adam-fowler commented on README.md
> +        cognitoBasicAuth.post("login", use: login)
You need to add guard middleware to get the 401 response.
```
let cognitoBasicAuth = app.grouped(CognitoBasicAuthenticator())
    .grouped(User.guardMiddleware())
cognitoBasicAuth.post("login", use: login)
```

2021-10-09 09:16 UTC, adam-fowler commented on README.md
You placed your basic authenticator example in the middle of my Id token example. Given the user is going to first implement the basic authenticator maybe place it above. See below about sub-headings. You'll need to remove the "Below is an example..." text from above

2021-10-25 17:10 UTC, adam-fowler commented
Hey @majortom64 do you intend to update this?

2021-10-25 17:15 UTC, majortom64 commented on README.md
Now that I have pretty much finished my example, I  will add some other examples and generally clean up my text. I should be have it done with in a day or two.

2024-10-18 07:47 UTC, closed without merging